{ pkgs ? import <nixpkgs> { config.allowUnfree = true; } }:

pkgs.mkShell {
  packages = with pkgs; [
    (python3.withPackages (ps: with ps; [
      numpy
      pytest
      flask
      openai
    ]))
    cmake
    clang
    vulkan-tools
    vulkan-headers
    vulkan-loader
    cudaPackages.cuda_cccl
    cudaPackages.cuda_cudart
    cudaPackages.cuda_cupti
    cudaPackages.cuda_nvcc
    cudaPackages.cuda_nvml_dev
    cudaPackages.cuda_nvrtc
    cudaPackages.cuda_nvtx
    cudaPackages.libcublas
    cudaPackages.libcufft
    cudaPackages.libcufile
    cudaPackages.libcurand
    cudaPackages.libcusolver
    cudaPackages.libcusparse
    cudaPackages.cudatoolkit
    cudaPackages.nccl
    cudaPackages.cudnn
    cudaPackages.cuda_opencl
    ripgrep
    curl
    glslang
    shaderc
    libclang
    libusb1
    eigen
    ninja
    pkg-config
    jsoncpp
    mesa
    libglvnd
    xorg.libX11
    xorg.libX11.dev
    xorg.libXext
    xorg.libXext.dev
    xorg.libXrandr
    xorg.libXrandr.dev
    opencv
    gst_all_1.gstreamer
    gst_all_1.gst-plugins-base
    gst_all_1.gst-plugins-good
    gst_all_1.gst-plugins-bad
    gst_all_1.gst-plugins-ugly
    gst_all_1.gst-libav
    gst_all_1.gst-vaapi
    ffmpeg
    x264
    pipewire
    libcap
    avahi
    libsysprof-capture
    sysprof
    pcre
    pcre2
    nlohmann_json
    cli11
    glib
    mount
    util-linux
    libnotify
    librsvg
    libselinux
    libsepol
    libarchive
    libtiff
    libdeflate
    hidapi
    openhmd
    SDL2
    cjson
    onnxruntime
    libuvc
    lerc
    libseccomp
    xz
    busybox
    libwebp
    libxdmcp
    expat
    dav1d
    libunwind
    harfbuzzFull
    harfbuzz
    libxml2
    pango
    cairo
    fribidi
    libthai
    libdatrie
    libdwarf
    elfutils
    orc
    wayland
    wayland-scanner
    wayland-utils
    doxygen
    libsurvive
    openvr
    opencomposite
    dbus
    libbsd
    libdrm
    rustup
    ccache
  ];
}
